version: '3'

services:
  wqp:
    build: .
    image: wqp
    networks:
      wqp:
        ipv4_address: ${WQP_SERVICES_IPV4}
    ports:
      - ${LOCALHOST_PORT}:8080
    environment:
      - WQP_DB_HOST=${WQP_DB_HOST}
      - WQP_DB_PORT=${WQP_DB_PORT}
      - WQP_DB_NAME=${WQP_DB_NAME}
      - WQP_DB_READ_ONLY_USERNAME=${WQP_DB_READ_ONLY_USERNAME}
      - WQP_DB_READ_ONLY_PASSWORD=${WQP_DB_READ_ONLY_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_CONTEXT_PATH=${SERVER_CONTEXT_PATH}
      - WQP_SERVICES_IPV4=${WQP_SERVICES_IPV4}
      - SITE_URL_BASE=${SITE_URL_BASE}
      - CODES_SERVICE_URL=${CODES_SERVICE_URL}
      - CODES_TIMEOUT_MILLI=${CODES_TIMEOUT_MILLI}
      - NLDI_TIMEOUT_MILLI=${NLDI_TIMEOUT_MILLI}
      - KML_STYLE_URL=${KML_STYLE_URL}
      - MAX_RESULT_ROWS=${MAX_RESULT_ROWS}
      - SWAGGER_DISPLAY_HOST=${SWAGGER_DISPLAY_HOST}
      - SWAGGER_DISPLAY_PATH=${SWAGGER_DISPLAY_PATH}
      - SWAGGER_DISPLAY_PROTOCOL=${SWAGGER_DISPLAY_PROTOCOL}
      - SWAGGER_SERVICES_LOOKUPS_URL=${SWAGGER_SERVICES_LOOKUPS_URL}
      - SWAGGER_SERVICES_CORE_URL=${SWAGGER_SERVICES_CORE_URL}
      - ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL}

networks:
  wqp:
    external:
      name: wqp
