version: '3'

services:
  wqp:
    build: .
    image: wqp
    networks:
      wqp:
        ipv4_address: ${WQP_SERVICES_IPV4}
    ports:
      - ${WQP_SERVICES_PORT}:8080
    environment:
      - COMMON_DATA_DIRECTORY=${COMMON_DATA_DIRECTORY}
      - APPLICATION_DATA_DIRECTORY=${APPLICATION_DATA_DIRECTORY}
    volumes:
      - ./secrets/common:${COMMON_DATA_DIRECTORY}
      - ./secrets/app:${APPLICATION_DATA_DIRECTORY}

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
