
spring:
  datasource:
    url: jdbc:postgresql://${WQP_DATABASE_ADDRESS}:${WQP_DATABASE_PORT}/${WQP_DATABASE_NAME}
    username: ${WQP_READ_ONLY_USERNAME}
    password: ${WQP_READ_ONLY_PASSWORD}
    hikari:
      auto-commit: false

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

springdoc:
  version: "@project.version@"

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    javax.management.mbeanserver: OFF

site:
  url:
    base: ${SITE_URL_BASE}
  swagger:
    apiDocsUrl: ${SERVER_CONTEXT_PATH}/v3/api-docs

codes:
  url: ${CODES_SERVICE_URL}
  mimeType: json
  timeout:
    milli: ${CODES_TIMEOUT_MILLI}

nldi:
  timeout:
    milli: ${NLDI_TIMEOUT_MILLI}

kml:
  style:
    url: ${KML_STYLE_URL}
max:
  result:
    rows: ${MAX_RESULT_ROWS}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
