# SAMPLE Swagger Services Configuration for WQP
swagger:
  services:
    - name: Lookups
      url: https://localhost:8443/qw_portal_services/v2/api-docs
      version: 2.0
    - name: NLDI
      url: https://cida.usgs.gov/nldi/v2/api-docs
      version: 2.0
    - name: Core WQP services
      url: http://localhost:8082/wqp/v2/api-docs
      version: 2.0