
spring:
  datasource:
    url: jdbc:postgresql://${WQP_DATABASE_ADDRESS}:${WQP_DATABASE_PORT}/${WQP_DATABASE_NAME}
    username: ${WQP_DB_READ_ONLY_USERNAME}
    password: ${WQP_DB_READ_ONLY_PASSWORD}
    hikari:
      auto-commit: false

  profiles:
    active: default,swagger

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

swagger:
  display:
    host: ${SWAGGER_DISPLAY_HOST}
    path: ${SWAGGER_DISPLAY_PATH}
    protocol: ${SWAGGER_DISPLAY_PROTOCOL}
  services:
    - name: Lookups
      url: ${SWAGGER_SERVICES_LOOKUPS_URL}/v2/api-docs
      version: 2.0
    - name: Core WQP services
      url: ${SWAGGER_SERVICES_CORE_URL}/v2/api-docs
      version: 2.0

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    javax.management.mbeanserver: OFF

site:
  url:
    base: ${SITE_URL_BASE}

codes:
  url: ${CODES_SERVICE_URL}
  mimeType: json
  timeout:
    milli: ${CODES_TIMEOUT_MILLI}

nldi:
  timeout:
    milli: ${NLDI_TIMEOUT_MILLI}

kml:
  style:
    url: ${KML_STYLE_URL}
max:
  result:
    rows: ${MAX_RESULT_ROWS}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
