# docker image path in artifactory
artifactoryPath: "wqp"
# name of the docker image
dockerImageName: "wqp-wqx-services"
# name of the git repo
gitRepoUrl: "https://github.com/NWQMC/WQP-WQX-Services.git"
# Jenkins credential for pushing back to repo
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
# name of the deploy job to trigger
deployJobName: "WQP-WQX-Services-deploy-wdfn"
# name of the project
projectName: "iow-allgemein"
# maximum amount of RAM for running Docker containers in rvice
memory: 512
# name of the application or service
applicationName: "data-services"
# port that is exposed by your container
containerPort: 8080
# string parameter specifying a path that ALB should use to verify that your application is alive
healthCheck: "/api/data/about/health"
# configuration repository paths
configRepoPath: "wma/docker/wdfn/data-services"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/api/data/*"
    priority: 428
  - type: redirect
    redirectConfig:
      host: "#{host}"
      path: "/api/data/#{path}"
      query: "#{query}"
      port: "#{port}"
      protocol: HTTPS
      statusCode: HTTP_301
    conditions:
      - /Result/*
      - /Station/*
      - /Activity/*
    priority: 427
tags:
  wma:costCenter: TBD
  wma:organization: iow
  wma:contact: TBD
  wma:taggingVersion: 0.0.1
  wma:project_id: wqp
